name: Storage
version: '${project.version}'
main: net.danh.storage.Storage
author: VoChiDanh
description: "${project.description}"
api-version: '1.13'
softdepend:
  - WorldGuard
  - PlaceholderAPI
commands:
  storage:
    description: Main command
    aliases:
      - kho
permissions:
  storage.toggle:
    description: Toggle permission
  storage.admin:
    description: Admin permission
