name: Storage
version: '${project.version}'
main: net.danh.storage.Storage
author: VoChiDanh
description: "${project.description}"
api-version: '1.13'
softdepend:
  - WorldGuard
  - PlaceholderAPI
commands:
  storage:
    description: Main command
    aliases:
      - kho
permissions:
  storage.toggle:
    description: Toggle permission
  storage.admin:
    description: Admin permission
  storage.admin.add:
    description: Admin add permission command
  storage.admin.remove:
    description: Admin remove permission command
  storage.admin.set:
    description: Admin set permission command
  storage.admin.max:
    description: Admin max permission command
  storage.admin.reload:
    description: Admin reload permission command
